baseURL: "https://www.JupyterHealth.org"
theme: "up-business-theme"
languageCode: "en-us"

#Top of the page and bottom of the page
title: "JupyterHealth"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Jupyter Health"
  description: "Open Software Platform for Health Data Ingestion and Management"
  images: 
    - "images/hero-image-jupyter.png"

  logo: "favicon.ico"

  favicons:
    themeColor: "#F37626"
    backgroundColor: "#4D4D4D"
    faviconColor: "#000000"

  social:
    # dribbble: "#"
    # instagram: "#"
    github: "https://github.com/jupyterhealth/"
    twitter: "https://twitter.com/JupyterHealth/"

  location:
    - "2594 Hearst Ave. Berkeley, CA 94720"

  contact:
    - "JupyterHealth@berkeley.edu"

  copyright: "© 2023 JupyterHealth All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About"
      url: "/about"
      weight: 2

    - name: "Community"
      url: "/community"
      weight: 3

    # - name: "People"
    #   url: "/people"
    #   weight: 4

    # - name: "Projects"
    #   url: "/projects"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

    - name: "docs"
      url: "https://jupyterhealth.github.io/software-documentation/"
      weight: 4

  # buttons:
  #   - name: "Join us"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "About"
      url: "/about"
      weight: 2

    - name: "Community"
      url: "/community"
      weight: 3
    
    # - name: "People"
    #   url: "/people"
    #   weight: 4

    # - name: "Projects"
    #   url: "/projects"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

    # - name: "docs"
    #   url: "https://jupyterhealth.github.io/software-documentation/"
    #   weight: 6


taxonomies:
  series: "series"
  tags: "tags"

# this allows the shortcode to work
markup:
  goldmark:
    renderer:
      unsafe: true
