baseURL: "/"
theme: "up-business-theme"
locale: "en-us"

title: "JupyterHealth"

summaryLength: 20

params:
  description: "Open Software Platform for Health Data Ingestion, Management, and Analysis"
  images:
    - "images/hero-image-jupyter.png"
  logo: "favicon.ico"

menus:
  main:
    - name: "Platform"
      url: "/#platform"
      weight: 1

    - name: "Use Cases"
      url: "/#use-cases"
      weight: 2

    - name: "Integration"
      url: "/#integration"
      weight: 3

    - name: "Team"
      url: "/#about"
      weight: 4

taxonomies:
  series: "series"
  tags: "tags"

# this allows the shortcode to work
markup:
  goldmark:
    renderer:
      unsafe: true
